name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  main:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master code
        uses: actions/checkout@v2
        with:
          path: master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build project
        run: |
          cd master
          ./gradlew :projector-client-web:browserProductionWebpack
          rm projector-client-web/build/distributions/*.map
          ./gradlew :docSrc:mkdocsBuild

      - name: Checkout gh-pages code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Copy distribution to gh-pages
        run: |  # todo: remove old files before copying the new ones
          cp master/projector-client-web/build/distributions/* gh-pages
          cp -r master/docSrc/build/mkdocs gh-pages
      - name: Commit and push
        run: |
          cd gh-pages
          git config --global user.email "servb@jetbrains.com"
          git config --global user.name "GH Actions Bot"
          git add -A
          git commit --allow-empty -m "Deploy revision $GITHUB_SHA" && git push
