name: Publish on Space

on:
  push:
    branches: [ master, publish_* ]
    tags:
      - "v*"
jobs:
  publish:
    name: publish on space
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        modules: [ agent-common, client-common, common, ij-common, server-core, util-agent, util-loading, util-logging ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SetUp Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Tag name  # Inspired from https://github.community/t/how-to-get-just-the-tag-name/16241/11
        id: tag_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Add properties
        run: |
          echo -n publishingVersion= >> gradle.properties
          echo ${{ github.sha }}  | head -c 8 >> gradle.properties
      - name: Clean
        run: ./gradlew clean
      - name: Publish to space
        run: ./gradlew :projector-${{ matrix.modules }}:publish -PmavenUsername=${{ secrets.SPACE_NAME }} -PmavenPassword=${{ secrets.SPACE_TOKEN }}
